[package]
name = "unw"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "stack unwinding"
license = "MIT OR Apache-2.0"

[dependencies]
fallible = "0.1"
null-terminated = "0.2.3"
